### PR TITLE
refactor: update pkg with the latest updates of upstream

### PR DESCRIPTION
**Pull request by bra-i-am**
**Description:**

This PR updates this package to integrate the latest changes of CSS variables support contained in the upstream [PR #689](https://github.com/openedx/frontend-platform/pull/689)

**Merge checklist:**

- [x] Published an NPM package with these changes [v8.0.1-alpha.1](https://www.npmjs.com/package/@edunext/frontend-platform/v/8.0.1-alpha.1)

**Additional info:**

Solved issue [#85 from eox-release](https://github.com/eduNEXT/eox-release/issues/85)

### CODE REVIEW

**Comment by bra-i-am** [comment]
**Update**

Tests are failing because of a `codecov` token we can't access, and the commit linter because of an upstream commit that couldn't be modified in the rebase.

**Comment by dcoa** [comment]
Please drop the temporal commit that adds the dist folder as specified in upstream's PR is there for testing purposes.

Thank you, @bra-i-am

**Comment by bra-i-am** [comment]
@dcoa: the commit was already dropped

**Comment by dcoa** [comment]
I was thinking that we should leaf only the design tokens commits and drop the upstream commits otherwise we are not using the version 7.x.x that suppose to be the base. 

@bra-i-am sorry for the inconvenience

**Pull request merged**
